apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          imagePullPolicy: Never
          image: expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: "mongodb://ticket-db:27017/ticket"
            - name: REDIS_HOST
              value: expiration-redis
