apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/user-regex: "true"
spec:
  rules:
    - host: ticket.dev
      http:
        paths:
          - path: /api/orders
            pathType: Prefix
            backend:
              serviceName: order
              servicePort: 4000
          - path: /api/payments
            pathType: Prefix
            backend:
              serviceName: payment
              servicePort: 5000
          - path: /api/tickets
            pathType: Prefix
            backend:
              serviceName: ticket
              servicePort: 2000
          - path: /api/users
            pathType: Prefix
            backend:
              serviceName: auth
              servicePort: 1000
          - path: /
            pathType: Prefix
            backend:
              serviceName: client-service
              servicePort: 3000
