apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          imagePullPolicy: Never
          image: ticket
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: "mongodb://ticket-db:27017/ticket"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticket
spec:
  selector:
    app: ticket
  ports:
    - name: ticket
      protocol: TCP
      port: 2000
      targetPort: 2000
